- name: Install NFS
  hosts: ansible02
  become: yes
  tasks:
    - name: Install NFS package
      yum:
        name: nfs-utils
        state: present
        
    - name: Create NFS share directory
      file:
        path: /share/workspaces
        state: directory

    - name: Create NFS share directory
      become: yes
      file:
        path: /share/workspaces
        state: directory

    - name: Configure NFS share
      lineinfile:
        path: /etc/exports
        line: "/share/workspaces *(rw,sync,no_root_squash,no_all_squash)"

    - name: Restart NFS service
      service:
        name: nfs
        state: restarted

    - name: Install NIS server packages
      become: yes
      yum:
        name: 
          - ypserv
        state: present

    - name: Set NIS domain name
      become: yes
      command: ypdomainname hoge

    - name: Add NISDOMAIN to sysconfig network
      become: yes
      lineinfile:
        path: /etc/sysconfig/network
        line: "NISDOMAIN=hoge"

    - name: Configure securenets
      become: yes
      copy:
        dest: /var/yp/securenets
        content: |
          255.255.255.255 127.0.0.1
          255.255.255.0   192.168.20.0

    - name: Start and enable NIS services
      become: yes
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - ypserv
        - yppasswdd
    
    - name: Upgrade pexpect
      become: yes
      pip:
        name: pexpect
        state: latest
        
    - name: Initialize NIS database
      expect:
        command: /usr/lib64/yp/ypinit -m
        responses:
          "next host to add: ": "\003"
          "Is this correct? ": "y"
        timeout: 60
    
