---
- hosts: node_all
  become: yes
  tasks:
    - name: Check if munge user exists
      command: id -u munge
      register: munge_user
      ignore_errors: true

    - name: Fail if munge user does not exist
      fail:
        msg: "Munge user does not exist"
      when: munge_user.rc != 0

    - name: Install munge
      apt:
        name: munge
        state: present

    - name: Copy munge.key from master
      copy:
        src: /share/workspaces/munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'

    - name: Enable munge service
      systemd:
        name: munge
        enabled: yes

    - name: Start munge service
      systemd:
        name: munge
        state: started

    - name: Check munge service status
      command: systemctl status munge
      register: result
      changed_when: false

    - debug: var=result.stdout_lines
...