---
- name: install mysql
  hosts: slurm_master
  become: yes
  vars_files:
    - password.yaml
  vars:
    ansible_become: yes
    ansible_become_method: sudo
    ansible_become_pass: "{{ vault_ansible_become_pass }}"
  tasks:
    - name: remove mysql*
      yum:
        name: mysql*
        state: absent

    - name: remove maria*
      yum:
        name: maria*
        state: absent

    - name: import mysql key
      rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

    - name: update yum
      yum:
        name: '*'
        state: latest

    # 本来ここには、yum localinstall -y https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
    #　を実行するための記述を入れたいが、エラーになるので一旦スキップ
    # 事前に上記を実行しておく事
    - name: install mysql repo
      become: yes
      shell: yum localinstall -y https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm

    - name: install mysql
      become: yes
      yum:
        name:
          - mysql-community-server
          - mysql-devel
        state: present

    - name: enable mysqld
      service:
        name: mysqld
        enabled: yes

    - name: start mysqld
      service:
        name: mysqld
        state: started
    
    - name: Extract temporary password line
      shell: grep 'root@localhost' /var/log/mysqld.log
      register: temp_password_line

    - name: Set sqlpassword variable
      set_fact:
        sqlpassword: "{{ temp_password_line.stdout | regex_search('root@localhost: (.*?)$', '\\1') | regex_replace('\\[|\\]', '') }}"

    - name: Display sqlpassword
      debug:
        var: sqlpassword
    
    
    - name: Update /etc/my.cnf
      lineinfile:
        path: /etc/my.cnf
        line: "{{ item.line }}"
        insertbefore: "{{ item.before }}"
      loop:
        - line: "character_set_server=utf8"
          before: "^datadir"
        - line: "default_password_lifetime=0"
          before: "^datadir"
        - line: "validate_password.policy=LOW"
          before: "^datadir"
        - line: "validate_password.length=4"
          before: "^datadir"
        - line: "log_timestamps=system"
          before: "^datadir"
        - line: "innodb_buffer_pool_size=1024M"
          before: "^datadir"
        - line: "innodb_log_file_size=64M"
          before: "^datadir"
        - line: "innodb_lock_wait_timeout=900"
          before: "^datadir"

    - name: Add client section to /etc/my.cnf
      blockinfile:
        path: /etc/my.cnf
        block: |
          [client]
          user=root
          password={{ sqlpassword }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        insertafter: EOF

    - name: Install necessary Python modules
      pip:
        name: "{{ item }}"
        executable: /home/terachi/anaconda3/bin/pip
      loop:
        - PyMySQL    # for Python 3
    
    - name: Check PyMySQL installation
      command: /home/terachi/anaconda3/bin/python -c "import pymysql"
    
    - name: Restart mysqld
      service:
        name: mysqld
        state: restarted
    
    - name: copy create_user.sql
      copy:
        src: /home/terachi/workspace/playbooks/create_user.sql
        dest: /tmp/create_user.sql

# sudo mysql_secure_installation
# を実行しパスワードを変更する
# その上で以下を実行
# sudo mysql -u root -p < /tmp/create_user.sql

# /etc/my.confのパスワードも変更する
#    - name: Import SQL file
#      shell: mysql -u root   < /tmp/create_user.sql




 
