---
- name: munge installation
  hosts: slurm_node4ubuntu
  become: yes
  vars_files:
    - password.yaml
  vars:
    ansible_become: yes
    ansible_become_method: sudo
    ansible_become_pass: "{{ vault_ansible_become_pass }}"
  tasks:
    - name: Install munge
      apt:
        name: munge
        state: present
    
    - name: Copy munge.key from slurm01 to control node
      fetch:
        src: /etc/munge/munge.key
        dest: /tmp/munge.key
      delegate_to: slurm01
      register: munge_path
    
    - name: debug
      debug:
        msg: "{{ munge_path }}"
    
    - name: Copy munge.key from control node to target
      copy:
        src: "{{ munge_path.dest }}"
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: 0400
    
    - name: Start munge service
      service:
        name: munge
        state: started


