---
- name: munge installation
  hosts: slurm_node4centos
  become: yes
  vars_files:
    - password.yaml
  vars:
    ansible_become: yes
    ansible_become_method: sudo
    ansible_become_pass: "{{ vault_ansible_become_pass }}"
  tasks:
    - name: Install bzip2-devel
      yum:
        name: 
          - openssl-devel
          - bzip2-devel
        state: present

    - name: Download munge
      get_url:
        url: https://github.com/dun/munge/releases/download/munge-0.5.14/munge-0.5.14.tar.xz
        dest: /tmp/munge-0.5.14.tar.xz

    - name: Download dun.gpg
      get_url:
        url: https://github.com/dun.gpg
        dest: /tmp/dun.gpg

    - name: Download munge asc
      get_url:
        url: https://github.com/dun/munge/releases/download/munge-0.5.14/munge-0.5.14.tar.xz.asc
        dest: /tmp/munge-0.5.14.tar.xz.asc

    - name: Build RPM package
      command: rpmbuild -tb /tmp/munge-0.5.14.tar.xz

    - name: Check if munge RPM packages are installed
      command: rpm -q munge munge-libs munge-devel
      register: rpm_check
      ignore_errors: true

    - name: Install munge RPM packages
      command: rpm -Uvh /root/rpmbuild/RPMS/x86_64/munge-0.5.14-1.el7.x86_64.rpm /root/rpmbuild/RPMS/x86_64/munge-devel-0.5.14-1.el7.x86_64.rpm /root/rpmbuild/RPMS/x86_64/munge-libs-0.5.14-1.el7.x86_64.rpm
      when: rpm_check.rc != 0

    - name: Check if munge debuginfo RPM package is installed
      command: rpm -q munge-debuginfo
      register: rpm_debuginfo_check
      ignore_errors: true

    - name: Install munge debuginfo RPM package
      command: rpm -Uvh /root/rpmbuild/RPMS/x86_64/munge-debuginfo-0.5.14-1.el7.x86_64.rpm
      when: rpm_debuginfo_check.rc != 0
    
    - name: Copy munge.key from slurm01 to control node
      fetch:
        src: /etc/munge/munge.key
        dest: /tmp/munge.key
      delegate_to: slurm01
      register: munge_path
    
    - name: debug
      debug:
        msg: "{{ munge_path }}"
    
    - name: Copy munge.key from control node to target
      copy:
        src: "{{ munge_path.dest }}"
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: 0400
    
    - name: Start munge service
      service:
        name: munge
        state: started


