---
- hosts: ansible01
  become: yes
  vars:
      ansible_python_interpreter: /home/terachi/anaconda3/bin/python

  tasks:
    - name: setenforce 0
      command: setenforce 0

    - name: stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: add group slurm
      group:
        name: slurm
        gid: 2000

    - name: add user slurm
      user:
        name: slurm
        uid: 2000
        group: slurm
        home: /home/slurm
        shell: /bin/bash

    - name: add group munge
      group:
        name: munge
        gid: 2020

    - name: add user munge
      user:
        name: munge
        uid: 2020
        group: munge
        home: /home/munge
        shell: /bin/bash

    - name: remove mysql*
      yum:
        name: mysql*
        state: absent

    - name: remove maria*
      yum:
        name: maria*
        state: absent

    - name: import mysql key
      rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

    - name: update yum
      yum:
        name: '*'
        state: latest

    # 本来ここには、yum localinstall -y https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
    #　を実行するための記述を入れたいが、エラーになるので一旦スキップ
    # 事前に上記を実行しておく事
    - name: install mysql repo
      become: yes
      shell: yum localinstall -y https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm

    - name: install mysql
      become: yes
      yum:
        name:
          - mysql-community-server
          - mysql-devel
        state: present

    - name: enable mysqld
      service:
        name: mysqld
        enabled: yes

    - name: start mysqld
      service:
        name: mysqld
        state: started
    
    - name: Extract temporary password line
      shell: grep 'root@localhost' /var/log/mysqld.log
      register: temp_password_line

    - name: Set sqlpassword variable
      set_fact:
        sqlpassword: "{{ temp_password_line.stdout | regex_search('root@localhost: (.*?)$', '\\1') }}"
    
    - name: Display sqlpassword
      debug:
        var: sqlpassword
    
    - name: Update /etc/my.cnf
      lineinfile:
        path: /etc/my.cnf
        line: "{{ item }}"
      with_items:
        - "character_set_server=utf8"
        - "default_password_lifetime=0"
        - "validate_password.policy=LOW"
        - "validate_password.length=4"
        - "log_timestamps=system"
        - "innodb_buffer_pool_size=1024M"
        - "innodb_log_file_size=64M"
        - "innodb_lock_wait_timeout=900"
    
    - name: Install necessary Python modules
      pip:
        name: "{{ item }}"
        executable: /home/terachi/anaconda3/bin/pip
      loop:
        - PyMySQL    # for Python 3
    
    - name: Check PyMySQL installation
      command: /home/terachi/anaconda3/bin/python -c "import pymysql"
    
    - name: Restart mysqld
      service:
        name: mysqld
        state: restarted
    
    - name: Create MySQL user
      mysql_user:
        login_user: root
        login_password: "{{ sqlpassword }}"
        name: slurm
        password: slurm
        host: localhost

    - name: Create MySQL database
      mysql_db:
        login_user: root
        login_password: "{{ sqlpassword }}"
        name: slurm_acct_db
        state: present

    - name: Grant privileges to the user
      mysql_user:
        login_user: root
        login_password: "{{ sqlpassword }}"
        name: slurm
        host: localhost
        priv: 'slurm_acct_db.*:ALL'
        append_privs: yes

    - name: update yum
      yum:
        name: '*'
        state: latest

    # 本来ここには、yum localinstall -y https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
    # 　を実行するための記述を入れたいが、エラーになるので一旦スキップ
    # 事前に上記を実行しておく事
    - name: install mysql repo
      become: yes
      shell: yum localinstall -y https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm

    - name: install mysql
      become: yes
      yum:
        name:
          - mysql-community-server
          - mysql-devel
        state: present

    - name: enable mysqld
      service:
        name: mysqld
        enabled: yes

    - name: start mysqld
      service:
        name: mysqld
        state: started

    - name: Extract temporary password line
      shell: grep 'root@localhost' /var/log/mysqld.log
      register: temp_password_line

    - name: Set sqlpassword variable
      set_fact:
        sqlpassword: "{{ temp_password_line.stdout | regex_search('root@localhost: (.*?)$', '\\1') }}"

    - name: Display sqlpassword
      debug:
        var: sqlpassword

    - name: Update /etc/my.cnf
      lineinfile:
        path: /etc/my.cnf
        line: "{{ item }}"
      with_items:
        - "character_set_server=utf8"
        - "default_password_lifetime=0"
        - "validate_password.policy=LOW"
        - "validate_password.length=4"
        - "log_timestamps=system"
        - "innodb_buffer_pool_size=1024M"
        - "innodb_log_file_size=64M"
        - "innodb_lock_wait_timeout=900"

    - name: Install necessary Python modules
      pip:
        name: PyMySQL
        executable: /home/terachi/anaconda3/bin/pip
  
    - name: Check PyMySQL installation
      command: /home/terachi/anaconda3/bin/python -c "import pymysql"

    - name: Restart mysqld
      service:
        name: mysqld
        state: restarted

    - name: Create MySQL user
      mysql_user:
        login_user: root
        login_password: "{{ sqlpassword }}"
        name: slurm
        password: slurm
        host: localhost

    - name: Create MySQL database
      mysql_db:
        login_user: root
        login_password: "{{ sqlpassword }}"
        name: slurm_acct_db
        state: present

    - name: Grant privileges to the user
      mysql_user:
        login_user: root
        login_password: "{{ sqlpassword }}"
        name: slurm
        host: localhost
        priv: 'slurm_acct_db.*:ALL'
        append_privs: yes

